name: helpers
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  path: ^1.8.3
  yaml: ^3.1.1
  args: ^2.4.0
  collection: ^1.17.1
  pub_semver: ^2.1.3
  http: ^1.0.0
  pub:
    git:
      url: https://github.com/dart-lang/pub
      ref: b21ac685bc64f6e81050ec0093aa83543d66e2fd
