inherit_from:
  - rubocop-default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'terraform/**/*'
    - 'elm/**/*'
    - 'docker/**/*'
    - 'git_submodules/**/*'
    - 'nuget/**/*'
    - 'gradle/**/*'
    - 'maven/**/*'
    - 'python/**/*'
    - 'hex/**/*'
    - 'cargo/**/*'
    - 'go_modules/**/*'
    - 'dep/**/*'
    - 'composer/**/*'
