version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - greysteil

  - package_manager: "php:composer"
    directory: "/composer/helpers"
    update_schedule: "live"

  - package_manager: "elixir:hex"
    directory: "/hex/helpers"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/npm_and_yarn/helpers"
    update_schedule: "live"

  - package_manager: "python"
    directory: "/python/helpers"
    update_schedule: "live"
