# Runs all ecosystems cached and concurrently.
name: Eco Smoke

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - docs/**
      - README.md
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: cargo, name: cargo, ecosystem: cargo }
          - { path: docker, name: docker, ecosystem: docker }
          - { path: git_submodules, name: git_submodules, ecosystem: gitsubmodule }
          - { path: github_actions, name: github_actions, ecosystem: github-actions }
          - { path: go_modules, name: go, ecosystem: gomod }
          - { path: gradle, name: gradle, ecosystem: gradle }
          - { path: maven, name: maven, ecosystem: maven }
          - { path: npm_and_yarn, name: npm, ecosystem: npm}
          - { path: npm_and_yarn, name: npm-remove-transitive, ecosystem: npm}
          - { path: npm_and_yarn, name: yarn-berry, ecosystem: npm}
          - { name: nuget, ecosystem: nuget }
          - { path: nuget, name: nuget, ecosystem: nuget }
          - { path: python, name: pip, ecosystem: pip }
          - { path: python, name: pipenv, ecosystem: pip}
          - { path: python, name: pip-compile, ecosystem: pip }
          - { path: python, name: poetry, ecosystem: pip }
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      if: github.event_name != 'workflow_dispatch'
      id: changes
      with:
        filters: |
          cargo:
            - Dockerfile.cargo
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'cargo/**'
          docker:
            - Dockerfile.docker
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'docker/**'
          git_submodules:
            - Dockerfile.git_submodules
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'git_submodules/**'
          github_actions:
            - Dockerfile.github_actions
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'github_actions/**'
          go:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'go_modules/**'
          gradle:
            - Dockerfile.gradle
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'gradle/**'
          maven:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'maven/**'
          npm:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'npm_and_yarn/**'
          'npm-remove-transitive':
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'npm_and_yarn/**'
          nuget:
            - Dockerfile.nuget
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'nuget/**'
          pip:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'python/**'
          'pip-compile':
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'python/**'
          pipenv:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'python/**'
          poetry:
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'python/**'
          'yarn-berry':
            - Dockerfile.updater-core
            - 'common/**'
            - 'updater/**'
            - 'npm_and_yarn/**'

    - name: Download CLI and test
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      run: |
        gh release download --repo dependabot/cli -p "*linux-amd64.tar.gz"
        tar xzvf *.tar.gz >/dev/null 2>&1
        ./dependabot --version
        URL=https://api.github.com/repos/dependabot/smoke-tests/contents/tests/smoke-${{ matrix.suite.name }}.yaml
        curl $(gh api $URL --jq .download_url) -o smoke.yaml

    # Download the Proxy cache. The job is ideally 100% cached so no real calls are made.
    - name: Download cache
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      run: |
        mkdir cache
        cd cache
        gh run download --repo dependabot/smoke-tests --name cache-${{ matrix.suite.name }}

    - name: Build updater core image
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build \
          -t "dependabot/dependabot-updater-core:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/dependabot/dependabot-updater-core \
          -f Dockerfile.updater-core \
          .

    - name: Build ecosystem image
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      env:
        DOCKER_BUILDKIT: 1
        OMNIBUS_VERSION: latest
      run: |
        docker build \
          -t "dependabot/updater:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/dependabot/dependabot-updater-core \
          --cache-from ghcr.io/dependabot/dependabot-updater-gomod \
          -f ${{ matrix.suite.path }}/Dockerfile \
          .

    - name: ${{ matrix.suite.name }}
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      env:
        LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -o pipefail
        ./dependabot test -f=smoke.yaml -o=result.yaml --cache=cache --timeout=20m --updater-image=dependabot/updater:latest 2>&1 | tee -a log.txt

    - name: Diff
      if: always()
      continue-on-error: true
      run: diff --ignore-space-change smoke.yaml result.yaml && echo "Contents are identical"

    - name: Create summary
      if: steps.changes.outputs[matrix.suite.name] == 'true'
      run: tail -n100 log.txt | grep -P '\d+/\d+ calls cached \(\d+%\)' >> $GITHUB_STEP_SUMMARY

    # No upload at the end:
    # - If a test is uncachable in some regard, the cache would grow unbound.
    # - We might want to consider erroring if the cache is changed.
