name: Push latest ecosystem images
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPDATER_IMAGE: "dependabot/updater-"
  UPDATER_IMAGE_MIRROR: "ghcr.io/dependabot/dependabot-updater-"
on:
  push:
    branches:
      - main
      - jakecoffman/eco-latest-caching-problems
    paths-ignore:
      - "CHANGELOG.md"
      - "common/lib/dependabot/version.rb"

jobs:
  date-version:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.DATE_BASED_VERSION }}
    steps:
      - id: date
        name: Set date based version
        # The v2 tag is the Updater image tag, not related to the core version.
        # This env var has to be set here so all versions are the same.
        run: |
          export DATE_BASED_VERSION=v2.0.$(date +%Y%m%d%H%M%S)
          echo "DATE_BASED_VERSION=$DATE_BASED_VERSION" >> $GITHUB_OUTPUT
  push-updater-image:
    name: Deploy
    runs-on: ubuntu-latest
    needs: date-version
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { name: go_modules, ecosystem: gomod }
          - { name: maven, ecosystem: maven }
          - { name: python, ecosystem: pip }
    env:
      TAG: ${{ github.sha }}
      NAME: ${{ matrix.suite.name }}
      ECOSYSTEM: ${{ matrix.suite.ecosystem }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build dependabot-updater-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-updater-core:$TAG" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-core \
            -f Dockerfile.updater-core \
            .

      - name: Build dependabot-updater image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "${UPDATER_IMAGE}${ECOSYSTEM}:$TAG" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}" \
            -f Dockerfile.${NAME} \
            .

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push branch image
        run: |
          docker tag "${UPDATER_IMAGE}${ECOSYSTEM}:$TAG" "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}:$TAG"
          docker push "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}:$TAG"

      - name: Push latest on main
        run: |
          docker tag "${UPDATER_IMAGE}${ECOSYSTEM}:$TAG" "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}:latest"
          docker tag "${UPDATER_IMAGE}${ECOSYSTEM}:$TAG" "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}:${{ needs.date-version.outputs.date }}"
          docker push --all-tags "${UPDATER_IMAGE_MIRROR}${ECOSYSTEM}"

      - name: Set summary
        run: |
          echo "updater uploaded with tag \`$TAG\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$UPDATER_IMAGE_MIRROR:$TAG" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
