name: CI-Eco
on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: go_modules, name: go_module, ci_node_total: 2, ci_node_index: 0, ecosystem: gomod }
          - { path: go_modules, name: go_module, ci_node_total: 2, ci_node_index: 1, ecosystem: gomod }
          - { path: maven, name: maven }
          - { path: python, name: python, ci_node_total: 2, ci_node_index: 0, ecosystem: pip }
          - { path: python, name: python, ci_node_total: 2, ci_node_index: 1, ecosystem: pip}
          - { path: python, name: python_slow, ci_node_total: 2, ci_node_index: 0, ecosystem: pip }
          - { path: python, name: python_slow, ci_node_total: 2, ci_node_index: 1, ecosystem: pip }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            python:
              - Dockerfile.updater-core
              - Dockerfile.python
              - 'common/**'
              - 'python/**'
              - '.github/workflows/ecosystem-ci.yml'
            maven:
              - Dockerfile.updater-core
              - Dockerfile.maven
              - 'common/**'
              - 'maven/**'
              - '.github/workflows/ecosystem-ci.yml'
            go_modules:
              - Dockerfile.updater-core
              - Dockerfile.go_modules
              - 'common/**'
              - 'go_modules/**'
              - '.github/workflows/ecosystem-ci.yml'

      - name: Build updater core image
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-updater-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-core \
            -f Dockerfile.updater-core \
            .

      - name: Build ecosystem image
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-updater-${{ matrix.suite.ecosystem }}:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from ghcr.io/dependabot/dependabot-updater-${{ matrix.suite.ecosystem }} \
            -f Dockerfile.${{ matrix.suite.path }} \
            .

      - name: Run ${{ matrix.suite.name }} tests
        if: steps.changes.outputs[matrix.suite.path] == 'true'
        run: |
          docker run \
            --env "CI=true" \
            --env "RAISE_ON_WARNINGS=true" \
            --env "DEPENDABOT_TEST_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            --env "SUITE_NAME=${{ matrix.suite.name }}" \
            --env "CI_NODE_TOTAL=${{ matrix.suite.ci_node_total }}" \
            --env "CI_NODE_INDEX=${{ matrix.suite.ci_node_index }}" \
            --rm dependabot/dependabot-updater-${{ matrix.suite.ecosystem }} bash -c \
            "cd /home/dependabot/${{ matrix.suite.path }} && ./script/ci-test"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: ./bin/lint
